# Test overview:
#    1 sampler (v4.3.3, named samp-4.3.3)
#       |
#       V
#    L1 agg (v4.3.3, named agg-4.3.3)
#       |
#       V
#    L2 agg (OVIS-4, named agg-4)
#
# Scenario
# - samp-4.3.3 started (1 set: meminfo)
# - agg-4.3.3 started, collecting sets from samp-4.3.3
# - agg-4 started, collecting sets from agg-4.3.3
# - ldms_ls to agg-4.3.3 & verify that it is not empty
# - ldms_ls to agg-4 & verify that it is the same as agg-4.3.3
# - kill samp-4.3.3
# - ldms_ls to agg-4.3.3 & verify that dir result is empty
# - ldms_ls to agg-4 & verify that dir result is empty

name: Compatibility test with OVIS-4.3.3

on:
  push:
    branches: 
      - darshan_ldms_Connector
  pull_request:
    branches:
      - darshan_ldms_Connector

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.platform }}
    #container:
    #    image: ovishpc/ovis-compat-centos7
    steps:
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
          #sudo apt-get update -y
          sudo apt-get install -y hdf5-tools libhdf5-openmpi-dev openmpi-bin
          #python -m pip install --upgrade pip
          #python -m pip install --upgrade pytest mpi4py
          # we need to build h5py with the system HDF5 lib backend
          export HDF5_MPI="ON"
          CC=mpicc python -m pip install --no-binary=h5py h5py
    - name: Clone LDMS
      uses: actions/checkout@v3
      with:
        repository: ovis-hpc/ovis
        path: ovis
        ref: OVIS-4
    - name: Clone Darshan Repo
      uses: actions/checkout@v3
      with:
        repository: Snell1224/darshan
        path: darshan
        ref: darshan_ldms_Connector
    - name: Install LDMS
      run: |
        cd ovis
        sh autogen.sh
        set -e
        mkdir -p build
        pushd build
        export CFLAGS="-O1 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -march=native"
        ../configure --prefix=/opt/ovis-4/  
        make 
        make install
    - name: Install darshan-runtime
      run: |
        cd darshan
        git branch -v
        export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/include/hdf5/openmpi/
        ls -ltr /usr/include/hdf5/openmpi/
        #mkdir darshan_install
        export DARSHAN_INSTALL_PATH=/opt/darshan_install
        git submodule update --init
        ./prepare.sh
        cd darshan-runtime
        mkdir build
        cd build
        CC=mpicc ../configure --prefix=$DARSHAN_INSTALL_PATH --with-log-path-by-env=DARSHAN_LOGPATH --with-ldms=/opt/ovis-4 --with-jobid-env=NONE --enable-hdf5-mod
        make
        make install
    - name: Install darshan-util
      run: |
        export DARSHAN_INSTALL_PATH=/opt/darshan_install
        cd darshan/darshan-util
        mkdir build
        cd build
        ../configure --prefix=$DARSHAN_INSTALL_PATH --enable-apxc-mod --enable-apmpi-mod
        make
        make install
    - name: Test Preparation and Run
      run : |
        echo "---setting Darshan environment---"
        export DARSHAN_INSTALL_PATH=/opt/darshan_install
        export LD_PRELOAD=$DARSHAN_INSTALL_PATH/lib/libdarshan.so
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DARSHAN_INSTALL_PATH/lib
        export DARSHAN_INSTALL_PATH=$DARSHAN_INSTALL_PATH
        #export HDF5_LIB=/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so
        export DXT_ENABLE_IO_TRACE=1
        echo "---setting LDMS environment---"
        TOP=/opt/ovis-4
        export LD_LIBRARY_PATH=$TOP/lib/:$TOP/lib:$LD_LIBRARY_PATH
        export LDMSD_PLUGIN_LIBPATH=$TOP/lib/ovis-ldms
        export ZAP_LIBPATH=$TOP/lib/ovis-ldms
        export PATH=$TOP/sbin:$TOP/bin:$PATH
        export PYTHONPATH=$TOP/lib/python3.6/site-packages
        echo "---setting Darshan-LDMS environment---"
        export DARSHAN_LDMS_STREAM=darshanConnector
        export DARSHAN_LDMS_PORT=10444
        export DARSHAN_LDMS_HOST=localhost
        export DARSHAN_LDMS_XPRT=sock
        export DARSHAN_LDMS_AUTH=none
        export DXT_ENABLE_LDMS=
        export STDIO_ENABLE_LDMS=
        export HDF5_ENABLE_LDMS=
        echo "---generating ldmsd configuration file---"
        cat > stream-samp-4.3.3.conf << EOF
        load name=hello_sampler
        config name=hello_sampler producer=host1 instance=host1/hello_sampler stream=darshanConnector component_id=1
        start name=hello_sampler interval=1000000 offset=0
        load name=stream_csv_store
        config name=stream_csv_store path=./streams/store container=csv stream=darshanConnector rolltype=3 rollover=500000
        EOF
        echo "---Starting ldmsd---"
        ldmsd -x sock:10444 -c stream-samp-4.3.3.conf -l /tmp/stream-samp-4.3.3.log -v DEBUG
        cat /tmp/stream-samp-4.3.3.log
        ldms_ls -p 10444 -h localhost -v
        echo "---Setting Test Case Variables---" 
        export PROG=mpi-io-test
        export DARSHAN_INSTALL_PATH=/opt/darshan_install
        export DARSHAN_TMP=/tmp/darshan-ldms-test
        export DARSHAN_PLATFORM=cray-module-stria
        export DARSHAN_TESTDIR=$PWD/darshan/darshan-test/regression
        export DARSHAN_LOGFILE=$DARSHAN_TMP/${PROG}.darshan
        echo "---Checking TMP Path---"
        if [ ! -x $DARSHAN_INSTALL_PATH/bin/darshan-dxt-parser ]; then
                echo "Error: $DARSHAN_PATH doesn't contain a valid Darshan install." 1>&2
                exit 1
        fi
        if [ ! -d $DARSHAN_TMP ]; then
                mkdir -p $DARSHAN_TMP
        fi
        if [ ! -d $DARSHAN_TMP ]; then
                echo "Error: unable to find or create $DARSHAN_TMP" 1>&2
                exit 1
        fi
        if [ ! -w $DARSHAN_TMP ]; then
                echo "Error: unable to write to $DARSHAN_TMP" 1>&2
                exit 1
        fi
        mpicc $DARSHAN_TESTDIR/test-cases/src/${PROG}.c -o $DARSHAN_TMP/${PROG}
        cd $DARSHAN_TMP
        ./${PROG} -f $DARSHAN_TMP/${PROG}.tmp.dat
        echo "---Parse Darshan file---"
        $DARSHAN_INSTALL_PATH/bin/darshan-parser --all $DARSHAN_LOGFILE > $DARSHAN_TMP/${PROG}.darshan.txt
        if [ $? -ne 0 ]; then
                echo "Error: failed to parse ${DARSHAN_LOGFILE}" 1>&2
                exit 1
        fi
        $DARSHAN_INSTALL_PATH/bin/darshan-dxt-parser --show-incomplete $DARSHAN_LOGFILE > $DARSHAN_TMP/${PROG}-dxt.darshan.txt
        if [ $? -ne 0 ]; then
                echo "Error: failed to parse ${DARSHAN_LOGFILE} for dxt tracing" 1>&2
        exit 1
        fi
    - name: Check Results
      run: |
        echo "---Checking Results---"
        export DARSHAN_TMP=/tmp/darshan-ldms-test
        export PROG=mpi-io-test
        ls -ltr /tmp/stream-samp-4.3.3.log
        ls -ltr streams/store/csv/
        cat /tmp/stream-samp-4.3.3.log
        ls -ltr csv/
        if [[ ! -f "$DARSHAN_TMP/${PROG}.darshan.txt" || ! -f "$DARSHAN_TMP/${PROG}-dxt.darshan.txt" ]]; then
                echo "One of the darshan log files do not exist."
                exit 1
        fi
        if [[ ! -f "streams/store/csv/darshanConnector*" ]]; then
                echo "CSV file does not exist."
                exit 1
        fi        
        echo "DONE!"
